In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/deep-learning-keras-tf-tutorial/master/13_dropout_layer/sonar_dataset.csv", header=None) 
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [6]:
df.shape

(208, 61)

In [10]:
# check for nan values
df.isnull().sum().sum()

0

In [11]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [12]:
df[60].value_counts() # label is not skewed

M    111
R     97
Name: 60, dtype: int64

In [13]:
X = df.drop(60, axis=1)
y = df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [14]:
y = pd.get_dummies(y, drop_first=True)
y.sample(5) # R --> 1 and M --> 0

     R
109  0
78   1
202  0
73   1
174  0

In [15]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [16]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0125,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0033,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0241,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0156,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [18]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
67,0.0368,0.0403,0.0317,0.0293,0.0820,0.1342,0.1161,0.0663,0.0155,0.0506,...,0.0058,0.0091,0.0160,0.0160,0.0081,0.0070,0.0135,0.0067,0.0078,0.0068
14,0.0124,0.0433,0.0604,0.0449,0.0597,0.0355,0.0531,0.0343,0.1052,0.2120,...,0.0078,0.0083,0.0057,0.0174,0.0188,0.0054,0.0114,0.0196,0.0147,0.0062
164,0.0163,0.0198,0.0202,0.0386,0.0752,0.1444,0.1487,0.1484,0.2442,0.2822,...,0.0027,0.0077,0.0026,0.0031,0.0083,0.0020,0.0084,0.0108,0.0083,0.0033
179,0.0394,0.0420,0.0446,0.0551,0.0597,0.1416,0.0956,0.0802,0.1618,0.2558,...,0.0118,0.0146,0.0040,0.0114,0.0032,0.0062,0.0101,0.0068,0.0053,0.0087
19,0.0126,0.0149,0.0641,0.1732,0.2565,0.2559,0.2947,0.4110,0.4983,0.5920,...,0.0153,0.0092,0.0035,0.0098,0.0121,0.0006,0.0181,0.0094,0.0116,0.0063

In [19]:
import tensorflow as tf
from tensorflow import keras

In [20]:
modeld = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
])

modeld.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

modeld.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7495 - accuracy: 0.5449
Epoch 2/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7085 - accuracy: 0.5449
Epoch 3/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6869 - accuracy: 0.5513
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7345 - accuracy: 0.4872
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6782 - accuracy: 0.5449
Epoch 6/100
20/20 [==============================] - 0s 5ms/step - loss: 0.7368 - accuracy: 0.4551
Epoch 7/100
20/20 [==============================] - 0s 5ms/step - loss: 0.7025 - accuracy: 0.5385
Epoch 8/100
20/20 [==============================] - 0s 5ms/step - loss: 0.7006 - accuracy: 0.5064
Epoch 9/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6862 - accuracy: 0.5256
Epoch 10/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6916 - accuracy: 0.5256
Epoch 11/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6890 - accuracy: 0.5385
Epoch 12/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6707 - accuracy: 0.5577
Epoch 13/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6878 - accuracy: 0.6154
Epoch 14/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6817 - accuracy: 0.5192
Epoch 15/100
20/20 [==============================] - 0s 6ms/step - loss: 0.6827 - accuracy: 0.6026
Epoch 16/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6553 - accuracy: 0.5897
Epoch 17/100
20/20 [==============================] - 0s 6ms/step - loss: 0.6812 - accuracy: 0.5513
Epoch 18/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6739 - accuracy: 0.5449
Epoch 19/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6379 - accuracy: 0.6410
Epoch 20/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6880 - accuracy: 0.5385
Epoch 21/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6645 - accuracy: 0.6090
Epoch 22/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6411 - accuracy: 0.6090
Epoch 23/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6218 - accuracy: 0.6410
Epoch 24/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6398 - accuracy: 0.5833
Epoch 25/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6581 - accuracy: 0.6154
Epoch 26/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6184 - accuracy: 0.6474
Epoch 27/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5958 - accuracy: 0.6859
Epoch 28/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5977 - accuracy: 0.6923
Epoch 29/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6164 - accuracy: 0.6474
Epoch 30/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6329 - accuracy: 0.6090
Epoch 31/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6027 - accuracy: 0.6667
Epoch 32/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6103 - accuracy: 0.6795
Epoch 33/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5788 - accuracy: 0.7372
Epoch 34/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6165 - accuracy: 0.6474
Epoch 35/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6036 - accuracy: 0.6538
Epoch 36/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5818 - accuracy: 0.6987
Epoch 37/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5648 - accuracy: 0.6987
Epoch 38/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5521 - accuracy: 0.7308
Epoch 39/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5646 - accuracy: 0.6859
Epoch 40/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5706 - accuracy: 0.7179
Epoch 41/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5078 - accuracy: 0.7628
Epoch 42/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5686 - accuracy: 0.7051
Epoch 43/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5527 - accuracy: 0.7500
Epoch 44/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5726 - accuracy: 0.7500
Epoch 45/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4941 - accuracy: 0.7500
Epoch 46/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5115 - accuracy: 0.7372
Epoch 47/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5832 - accuracy: 0.7308
Epoch 48/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5332 - accuracy: 0.7308
Epoch 49/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5389 - accuracy: 0.7308
Epoch 50/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4888 - accuracy: 0.7821
Epoch 51/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4610 - accuracy: 0.8013
Epoch 52/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4993 - accuracy: 0.7628
Epoch 53/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5096 - accuracy: 0.8013
Epoch 54/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4824 - accuracy: 0.7756
Epoch 55/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4916 - accuracy: 0.7756
Epoch 56/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5178 - accuracy: 0.7308
Epoch 57/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5209 - accuracy: 0.7115
Epoch 58/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4833 - accuracy: 0.7756
Epoch 59/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4302 - accuracy: 0.8205
Epoch 60/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4282 - accuracy: 0.8397
Epoch 61/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4740 - accuracy: 0.7949
Epoch 62/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4639 - accuracy: 0.7949
Epoch 63/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4224 - accuracy: 0.8333
Epoch 64/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4494 - accuracy: 0.7821
Epoch 65/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4644 - accuracy: 0.7564
Epoch 66/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.8718
Epoch 67/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5136 - accuracy: 0.7564
Epoch 68/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4373 - accuracy: 0.8141
Epoch 69/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3936 - accuracy: 0.8141
Epoch 70/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4002 - accuracy: 0.8269
Epoch 71/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4151 - accuracy: 0.8141
Epoch 72/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4346 - accuracy: 0.8077
Epoch 73/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3872 - accuracy: 0.7885
Epoch 74/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4139 - accuracy: 0.7885
Epoch 75/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4453 - accuracy: 0.8526
Epoch 76/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3465 - accuracy: 0.8782
Epoch 77/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3991 - accuracy: 0.8333
Epoch 78/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3783 - accuracy: 0.8590
Epoch 79/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3531 - accuracy: 0.8654
Epoch 80/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3673 - accuracy: 0.8782
Epoch 81/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3060 - accuracy: 0.8718
Epoch 82/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3935 - accuracy: 0.8333
Epoch 83/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3998 - accuracy: 0.8269
Epoch 84/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3522 - accuracy: 0.8462
Epoch 85/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3489 - accuracy: 0.8910
Epoch 86/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3121 - accuracy: 0.8910
Epoch 87/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3435 - accuracy: 0.8462
Epoch 88/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3439 - accuracy: 0.8846
Epoch 89/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3463 - accuracy: 0.8590
Epoch 90/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3759 - accuracy: 0.8269
Epoch 91/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3063 - accuracy: 0.8910
Epoch 92/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3846 - accuracy: 0.8269
Epoch 93/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3149 - accuracy: 0.8910
Epoch 94/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3190 - accuracy: 0.8590
Epoch 95/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2868 - accuracy: 0.9038
Epoch 96/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2984 - accuracy: 0.8526
Epoch 97/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2767 - accuracy: 0.9038
Epoch 98/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3108 - accuracy: 0.8846
Epoch 99/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2603 - accuracy: 0.8910
Epoch 100/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3032 - accuracy: 0.8846

In [21]:
modeld.evaluate(X_test, y_test)

2/2 [==============================] - 0s 6ms/step - loss: 0.3729 - accuracy: 0.8462

[0.3729289770126343, 0.8461538553237915]

In [22]:
y_pred = modeld.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

[4.2660638e-05 6.6951400e-01 9.1802084e-01 9.0837777e-03 9.9688601e-01
 8.9638281e-01 3.7295175e-01 9.9829996e-01 2.4935007e-02 9.9862576e-01]
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]

In [23]:
y_test[:10]

     R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [24]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85        27
           1       0.84      0.84      0.84        25

    accuracy                           0.85        52
   macro avg       0.85      0.85      0.85        52
weighted avg       0.85      0.85      0.85        52